# Build stage
FROM node:18-alpine AS base
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
COPY .env .env
RUN npm run build

# Run Stage
FROM node:18-alpine
WORKDIR /app
# Copy built application from the build stage
COPY --from=base /app /app
EXPOSE 3000
CMD ["npm", "start"]
